//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecureuil.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ecureuil.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About -.
        /// </summary>
        internal static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add1 {
            get {
                object obj = ResourceManager.GetObject("add1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can add new sources by clicking the Add button, or use the Discover feature; this presents a list of available sources from which you can add them..
        /// </summary>
        internal static string addSourcesText {
            get {
                return ResourceManager.GetString("addSourcesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source URL.
        /// </summary>
        internal static string addSourceURL {
            get {
                return ResourceManager.GetString("addSourceURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn how to add your own source to the Discovery list.
        /// </summary>
        internal static string addYourOwn {
            get {
                return ResourceManager.GetString("addYourOwn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more.
        /// </summary>
        internal static string addYourOwn2 {
            get {
                return ResourceManager.GetString("addYourOwn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all_apps.
        /// </summary>
        internal static string all_apps {
            get {
                return ResourceManager.GetString("all_apps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files.
        /// </summary>
        internal static string allFiles {
            get {
                return ResourceManager.GetString("allFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Windows versions.
        /// </summary>
        internal static string allWindowsVersion {
            get {
                return ResourceManager.GetString("allWindowsVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app.
        /// </summary>
        internal static string app {
            get {
                return ResourceManager.GetString("app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string appAll {
            get {
                return ResourceManager.GetString("appAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by .
        /// </summary>
        internal static string appAuthor {
            get {
                return ResourceManager.GetString("appAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compatible with this system (.
        /// </summary>
        internal static string appCompatible {
            get {
                return ResourceManager.GetString("appCompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop app.
        /// </summary>
        internal static string appDesktop {
            get {
                return ResourceManager.GetString("appDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Ecureuil.
        /// </summary>
        internal static string appDetailTitle {
            get {
                return ResourceManager.GetString("appDetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App developer.
        /// </summary>
        internal static string appDeveloper {
            get {
                return ResourceManager.GetString("appDeveloper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        internal static string appFree {
            get {
                return ResourceManager.GetString("appFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immersive (Metro/UWP).
        /// </summary>
        internal static string appImmersive {
            get {
                return ResourceManager.GetString("appImmersive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installer package.
        /// </summary>
        internal static string appInstaller {
            get {
                return ResourceManager.GetString("appInstaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neutral.
        /// </summary>
        internal static string appLanguageNeutral {
            get {
                return ResourceManager.GetString("appLanguageNeutral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to applications.
        /// </summary>
        internal static string applications {
            get {
                return ResourceManager.GetString("applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications.
        /// </summary>
        internal static string ApplicationsText {
            get {
                return ResourceManager.GetString("ApplicationsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string apply {
            get {
                return ResourceManager.GetString("apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No description provided..
        /// </summary>
        internal static string appNoDescription {
            get {
                return ResourceManager.GetString("appNoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not compatible (.
        /// </summary>
        internal static string appNotCompatible {
            get {
                return ResourceManager.GetString("appNotCompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portable exe.
        /// </summary>
        internal static string appPortable {
            get {
                return ResourceManager.GetString("appPortable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string appSourceColumn1 {
            get {
                return ResourceManager.GetString("appSourceColumn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string appSourceColumn2 {
            get {
                return ResourceManager.GetString("appSourceColumn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string appSourceColumn3 {
            get {
                return ResourceManager.GetString("appSourceColumn3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it compatible?.
        /// </summary>
        internal static string appSourceColumn4 {
            get {
                return ResourceManager.GetString("appSourceColumn4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compatible.
        /// </summary>
        internal static string appSourceCompatible {
            get {
                return ResourceManager.GetString("appSourceCompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not compatible.
        /// </summary>
        internal static string appSourceNotCompatible {
            get {
                return ResourceManager.GetString("appSourceNotCompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The app comes from .
        /// </summary>
        internal static string appSourceText1 {
            get {
                return ResourceManager.GetString("appSourceText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  source, from .
        /// </summary>
        internal static string appSourceText2 {
            get {
                return ResourceManager.GetString("appSourceText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  category..
        /// </summary>
        internal static string appSourceText3 {
            get {
                return ResourceManager.GetString("appSourceText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app is in the .
        /// </summary>
        internal static string appSourceText4 {
            get {
                return ResourceManager.GetString("appSourceText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploader: .
        /// </summary>
        internal static string appSourceTextUploader {
            get {
                return ResourceManager.GetString("appSourceTextUploader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown.
        /// </summary>
        internal static string appSourceUnknown {
            get {
                return ResourceManager.GetString("appSourceUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial.
        /// </summary>
        internal static string appTrial {
            get {
                return ResourceManager.GetString("appTrial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Architecture: .
        /// </summary>
        internal static string architecture {
            get {
                return ResourceManager.GetString("architecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Architecture.
        /// </summary>
        internal static string architecture2 {
            get {
                return ResourceManager.GetString("architecture2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string author {
            get {
                return ResourceManager.GetString("author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string back {
            get {
                return ResourceManager.GetString("back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap back1 {
            get {
                object obj = ResourceManager.GetObject("back1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache.
        /// </summary>
        internal static string cacheTitle {
            get {
                return ResourceManager.GetString("cacheTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog: .
        /// </summary>
        internal static string catalogPrefix {
            get {
                return ResourceManager.GetString("catalogPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category: .
        /// </summary>
        internal static string category {
            get {
                return ResourceManager.GetString("category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string category2 {
            get {
                return ResourceManager.GetString("category2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cat.
        /// </summary>
        internal static string categoryNode {
            get {
                return ResourceManager.GetString("categoryNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compatibility.
        /// </summary>
        internal static string compatibility {
            get {
                return ResourceManager.GetString("compatibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        internal static string confirmDeleteTitle {
            get {
                return ResourceManager.GetString("confirmDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap copylink {
            get {
                object obj = ResourceManager.GetObject("copylink", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created on: .
        /// </summary>
        internal static string createdOn {
            get {
                return ResourceManager.GetString("createdOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        internal static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date created:.
        /// </summary>
        internal static string dateCreated {
            get {
                return ResourceManager.GetString("dateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd/MM/yyyy.
        /// </summary>
        internal static string dateFormat {
            get {
                return ResourceManager.GetString("dateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date uploaded:.
        /// </summary>
        internal static string dateUpload {
            get {
                return ResourceManager.GetString("dateUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --.
        /// </summary>
        internal static string defaultDashTime {
            get {
                return ResourceManager.GetString("defaultDashTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.0.
        /// </summary>
        internal static string defaultZeroSize {
            get {
                return ResourceManager.GetString("defaultZeroSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00:00:00.
        /// </summary>
        internal static string defaultZeroTime {
            get {
                return ResourceManager.GetString("defaultZeroTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete all installed sources?.
        /// </summary>
        internal static string deleteAllSourcesConfirm {
            get {
                return ResourceManager.GetString("deleteAllSourcesConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected cache files ({0} item(s)) and their cached images?.
        /// </summary>
        internal static string deleteCacheConfirm {
            get {
                return ResourceManager.GetString("deleteCacheConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete cache.
        /// </summary>
        internal static string deleteCacheTitle {
            get {
                return ResourceManager.GetString("deleteCacheTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete / Remove.
        /// </summary>
        internal static string deleteRemove {
            get {
                return ResourceManager.GetString("deleteRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove the source &apos;{0}&apos;?.
        /// </summary>
        internal static string deleteSourceConfirm {
            get {
                return ResourceManager.GetString("deleteSourceConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string details {
            get {
                return ResourceManager.GetString("details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap disable {
            get {
                object obj = ResourceManager.GetObject("disable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string disabled {
            get {
                return ResourceManager.GetString("disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disabled..
        /// </summary>
        internal static string disabled2 {
            get {
                return ResourceManager.GetString("disabled2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable source.
        /// </summary>
        internal static string disableSource {
            get {
                return ResourceManager.GetString("disableSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disc.
        /// </summary>
        internal static string disc {
            get {
                return ResourceManager.GetString("disc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to discoverSources.
        /// </summary>
        internal static string discoverNode {
            get {
                return ResourceManager.GetString("discoverNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover sources.
        /// </summary>
        internal static string discoverSources {
            get {
                return ResourceManager.GetString("discoverSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://fraaaaa4.github.io/ecureuil-discovery-sources/sources.json.
        /// </summary>
        internal static string discoveryURL {
            get {
                return ResourceManager.GetString("discoveryURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download {
            get {
                object obj = ResourceManager.GetObject("download", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download complete..
        /// </summary>
        internal static string downloadComplete {
            get {
                return ResourceManager.GetString("downloadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download failed.
        /// </summary>
        internal static string downloadFailed {
            get {
                return ResourceManager.GetString("downloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download a file.
        /// </summary>
        internal static string downloadFile {
            get {
                return ResourceManager.GetString("downloadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re trying to download.
        /// </summary>
        internal static string downloadFile2 {
            get {
                return ResourceManager.GetString("downloadFile2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from the source.
        /// </summary>
        internal static string downloadFile3 {
            get {
                return ResourceManager.GetString("downloadFile3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to download application index from:\n.
        /// </summary>
        internal static string downloadSourceError {
            get {
                return ResourceManager.GetString("downloadSourceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error downloading source index: .
        /// </summary>
        internal static string downloadSourceError2 {
            get {
                return ResourceManager.GetString("downloadSourceError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download error.
        /// </summary>
        internal static string downloadSourceErrorTitle {
            get {
                return ResourceManager.GetString("downloadSourceErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download URLis not available..
        /// </summary>
        internal static string downloadURL {
            get {
                return ResourceManager.GetString("downloadURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ecureuil.
        /// </summary>
        internal static string ecureuil {
            get {
                return ResourceManager.GetString("ecureuil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap enable {
            get {
                object obj = ResourceManager.GetObject("enable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string enabled {
            get {
                return ResourceManager.GetString("enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enabled..
        /// </summary>
        internal static string enabled2 {
            get {
                return ResourceManager.GetString("enabled2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable source.
        /// </summary>
        internal static string enableSource {
            get {
                return ResourceManager.GetString("enableSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error:.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string error2 {
            get {
                return ResourceManager.GetString("error2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exe.
        /// </summary>
        internal static string exe {
            get {
                return ResourceManager.GetString("exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension: .
        /// </summary>
        internal static string extension {
            get {
                return ResourceManager.GetString("extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File details.
        /// </summary>
        internal static string fileDetails {
            get {
                return ResourceManager.GetString("fileDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        internal static string files {
            get {
                return ResourceManager.GetString("files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications.
        /// </summary>
        internal static string firstCategoryNode {
            get {
                return ResourceManager.GetString("firstCategoryNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward.
        /// </summary>
        internal static string forward {
            get {
                return ResourceManager.GetString("forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap forward1 {
            get {
                object obj = ResourceManager.GetObject("forward1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string general {
            get {
                return ResourceManager.GetString("general", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string generalCategory {
            get {
                return ResourceManager.GetString("generalCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic.
        /// </summary>
        internal static string generic {
            get {
                return ResourceManager.GetString("generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GroupBy {
            get {
                object obj = ResourceManager.GetObject("GroupBy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group by:.
        /// </summary>
        internal static string groupByLabel {
            get {
                return ResourceManager.GetString("groupByLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immersive App.
        /// </summary>
        internal static string immersiveApp {
            get {
                return ResourceManager.GetString("immersiveApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immersive tag.
        /// </summary>
        internal static string immersiveTag {
            get {
                return ResourceManager.GetString("immersiveTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info: .
        /// </summary>
        internal static string infoPrefix {
            get {
                return ResourceManager.GetString("infoPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap install {
            get {
                object obj = ResourceManager.GetObject("install", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to installed.
        /// </summary>
        internal static string installedNode {
            get {
                return ResourceManager.GetString("installedNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of installed sources:.
        /// </summary>
        internal static string installedSourcesList {
            get {
                return ResourceManager.GetString("installedSourcesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installer.
        /// </summary>
        internal static string installer {
            get {
                return ResourceManager.GetString("installer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid URL.
        /// </summary>
        internal static string invalidUrlTitle {
            get {
                return ResourceManager.GetString("invalidUrlTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        internal static string languages {
            get {
                return ResourceManager.GetString("languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last updated:.
        /// </summary>
        internal static string lastUpdated {
            get {
                return ResourceManager.GetString("lastUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        internal static string link {
            get {
                return ResourceManager.GetString("link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open link:.
        /// </summary>
        internal static string linkError {
            get {
                return ResourceManager.GetString("linkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links &amp; online references from .
        /// </summary>
        internal static string linksName {
            get {
                return ResourceManager.GetString("linksName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local source.
        /// </summary>
        internal static string localSource {
            get {
                return ResourceManager.GetString("localSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing URL.
        /// </summary>
        internal static string missingUrlTitle {
            get {
                return ResourceManager.GetString("missingUrlTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to msi.
        /// </summary>
        internal static string msi {
            get {
                return ResourceManager.GetString("msi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (None).
        /// </summary>
        internal static string none {
            get {
                return ResourceManager.GetString("none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string notAvailable {
            get {
                return ResourceManager.GetString("notAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap oepn {
            get {
                object obj = ResourceManager.GetObject("oepn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string open {
            get {
                return ResourceManager.GetString("open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap orderBy {
            get {
                object obj = ResourceManager.GetObject("orderBy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order by:.
        /// </summary>
        internal static string orderByLabel {
            get {
                return ResourceManager.GetString("orderByLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original date.
        /// </summary>
        internal static string originalDate {
            get {
                return ResourceManager.GetString("originalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string other {
            get {
                return ResourceManager.GetString("other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string pause {
            get {
                return ResourceManager.GetString("pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a source URL..
        /// </summary>
        internal static string pleaseEnterSourceUrl {
            get {
                return ResourceManager.GetString("pleaseEnterSourceUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid URL..
        /// </summary>
        internal static string pleaseEnterValidUrl {
            get {
                return ResourceManager.GetString("pleaseEnterValidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portable.
        /// </summary>
        internal static string portable {
            get {
                return ResourceManager.GetString("portable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portable tag.
        /// </summary>
        internal static string portableTag {
            get {
                return ResourceManager.GetString("portableTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        internal static string progress {
            get {
                return ResourceManager.GetString("progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string properties {
            get {
                return ResourceManager.GetString("properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to README.md.
        /// </summary>
        internal static string readmeFile {
            get {
                return ResourceManager.GetString("readmeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string refresh {
            get {
                return ResourceManager.GetString("refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap refresh1 {
            get {
                object obj = ResourceManager.GetObject("refresh1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh all the sources.
        /// </summary>
        internal static string refreshAll {
            get {
                return ResourceManager.GetString("refreshAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No cache item selected. Do you want to redownload cache for ALL installed sources and applications?.
        /// </summary>
        internal static string refreshAllCacheConfirm {
            get {
                return ResourceManager.GetString("refreshAllCacheConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Cache.
        /// </summary>
        internal static string refreshCacheTitle {
            get {
                return ResourceManager.GetString("refreshCacheTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh current view.
        /// </summary>
        internal static string refreshCurrentTooltip {
            get {
                return ResourceManager.GetString("refreshCurrentTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh only the selected source(s).
        /// </summary>
        internal static string refreshOnly {
            get {
                return ResourceManager.GetString("refreshOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote source.
        /// </summary>
        internal static string remoteSource {
            get {
                return ResourceManager.GetString("remoteSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as....
        /// </summary>
        internal static string saveAs {
            get {
                return ResourceManager.GetString("saveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lets you choose now where to save the file.
        /// </summary>
        internal static string saveAsTooltip {
            get {
                return ResourceManager.GetString("saveAsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saves the file to the destination specified in Settings.
        /// </summary>
        internal static string saveTooltip {
            get {
                return ResourceManager.GetString("saveTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshot.
        /// </summary>
        internal static string screenshot {
            get {
                return ResourceManager.GetString("screenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        internal static string searchPlaceholder {
            get {
                return ResourceManager.GetString("searchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in current view.
        /// </summary>
        internal static string searchTooltip {
            get {
                return ResourceManager.GetString("searchTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sources.
        /// </summary>
        internal static string secondCategoryNode {
            get {
                return ResourceManager.GetString("secondCategoryNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one cache item to delete..
        /// </summary>
        internal static string selectCacheToDelete {
            get {
                return ResourceManager.GetString("selectCacheToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select download folder.
        /// </summary>
        internal static string selectDownload {
            get {
                return ResourceManager.GetString("selectDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup in a file ZIP.
        /// </summary>
        internal static string setupZip {
            get {
                return ResourceManager.GetString("setupZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It looks like you&apos;ve downloaded a non-portable app, packaged in a zip file. What do you want to do?.
        /// </summary>
        internal static string setupZipLabel {
            get {
                return ResourceManager.GetString("setupZipLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string size {
            get {
                return ResourceManager.GetString("size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size: .
        /// </summary>
        internal static string sizePrefix {
            get {
                return ResourceManager.GetString("sizePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source:.
        /// </summary>
        internal static string source {
            get {
                return ResourceManager.GetString("source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  source.
        /// </summary>
        internal static string source2 {
            get {
                return ResourceManager.GetString("source2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string source3 {
            get {
                return ResourceManager.GetString("source3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sources.
        /// </summary>
        internal static string source4 {
            get {
                return ResourceManager.GetString("source4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source added successfully..
        /// </summary>
        internal static string sourceAdded {
            get {
                return ResourceManager.GetString("sourceAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source details.
        /// </summary>
        internal static string sourceDetails {
            get {
                return ResourceManager.GetString("sourceDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source is now.
        /// </summary>
        internal static string sourceIsNow {
            get {
                return ResourceManager.GetString("sourceIsNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to src.
        /// </summary>
        internal static string sourceMinus {
            get {
                return ResourceManager.GetString("sourceMinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source refreshed successfully..
        /// </summary>
        internal static string sourceRefreshed {
            get {
                return ResourceManager.GetString("sourceRefreshed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to refresh source.
        /// </summary>
        internal static string sourceRefreshFail {
            get {
                return ResourceManager.GetString("sourceRefreshFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your installed sources, or discover new ones..
        /// </summary>
        internal static string sourcesDescription {
            get {
                return ResourceManager.GetString("sourcesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add sources.
        /// </summary>
        internal static string sourcesGroup {
            get {
                return ResourceManager.GetString("sourcesGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sources.
        /// </summary>
        internal static string sourcesNode {
            get {
                return ResourceManager.GetString("sourcesNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard App.
        /// </summary>
        internal static string standardApp {
            get {
                return ResourceManager.GetString("standardApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed components.
        /// </summary>
        internal static string thirdCategoryNode {
            get {
                return ResourceManager.GetString("thirdCategoryNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time remaining:.
        /// </summary>
        internal static string time {
            get {
                return ResourceManager.GetString("time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time elapsed:.
        /// </summary>
        internal static string timeElapsed {
            get {
                return ResourceManager.GetString("timeElapsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbar.
        /// </summary>
        internal static string toolbar {
            get {
                return ResourceManager.GetString("toolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap uninstall {
            get {
                object obj = ResourceManager.GetObject("uninstall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to uninstall.
        /// </summary>
        internal static string uninstallFailure {
            get {
                return ResourceManager.GetString("uninstallFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to uninstall.
        /// </summary>
        internal static string uninstallQuestion {
            get {
                return ResourceManager.GetString("uninstallQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        internal static string uninstallString {
            get {
                return ResourceManager.GetString("uninstallString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uninstalled successfully.
        /// </summary>
        internal static string uninstallSuccess {
            get {
                return ResourceManager.GetString("uninstallSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since this was installed via a setup, remember to uninstall it from Control Panel..
        /// </summary>
        internal static string uninstallWarning {
            get {
                return ResourceManager.GetString("uninstallWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Author.
        /// </summary>
        internal static string unknownAuthor {
            get {
                return ResourceManager.GetString("unknownAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Uploader.
        /// </summary>
        internal static string unknownUploader {
            get {
                return ResourceManager.GetString("unknownUploader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date uploaded.
        /// </summary>
        internal static string uploadedDate {
            get {
                return ResourceManager.GetString("uploadedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploader.
        /// </summary>
        internal static string uploader {
            get {
                return ResourceManager.GetString("uploader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL must start with http:// or https://.
        /// </summary>
        internal static string urlMustStartWithHttp {
            get {
                return ResourceManager.GetString("urlMustStartWithHttp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Sources Index.
        /// </summary>
        internal static string userSourcesIndex {
            get {
                return ResourceManager.GetString("userSourcesIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string version {
            get {
                return ResourceManager.GetString("version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows .
        /// </summary>
        internal static string windowsPrefix {
            get {
                return ResourceManager.GetString("windowsPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zip.
        /// </summary>
        internal static string zip {
            get {
                return ResourceManager.GetString("zip", resourceCulture);
            }
        }
    }
}
